p8105\_hw2\_kz2411
================
Keming Zhang
10/9/2021

## Problem 1

``` r
# read and clean Mr. Trash Wheel
wheel_data <- read_excel('./data/Trash-Wheel-Collection-Totals-7-2020-2.xlsx',
                         sheet = "Mr. Trash Wheel", range = "A2:N534") %>%
  janitor::clean_names() %>%
  drop_na(dumpster) %>%
  mutate(
    sports_balls = round(sports_balls, digits = 0)
  )
wheel_data
```

    ## # A tibble: 453 × 14
    ##    dumpster month  year date                weight_tons volume_cubic_yards
    ##       <dbl> <chr> <dbl> <dttm>                    <dbl>              <dbl>
    ##  1        1 May    2014 2014-05-16 00:00:00        4.31                 18
    ##  2        2 May    2014 2014-05-16 00:00:00        2.74                 13
    ##  3        3 May    2014 2014-05-16 00:00:00        3.45                 15
    ##  4        4 May    2014 2014-05-17 00:00:00        3.1                  15
    ##  5        5 May    2014 2014-05-17 00:00:00        4.06                 18
    ##  6        6 May    2014 2014-05-20 00:00:00        2.71                 13
    ##  7        7 May    2014 2014-05-21 00:00:00        1.91                  8
    ##  8        8 May    2014 2014-05-28 00:00:00        3.7                  16
    ##  9        9 June   2014 2014-06-05 00:00:00        2.52                 14
    ## 10       10 June   2014 2014-06-11 00:00:00        3.76                 18
    ## # … with 443 more rows, and 8 more variables: plastic_bottles <dbl>,
    ## #   polystyrene <dbl>, cigarette_butts <dbl>, glass_bottles <dbl>,
    ## #   grocery_bags <dbl>, chip_bags <dbl>, sports_balls <dbl>,
    ## #   homes_powered <dbl>

``` r
# read and clean precipitation data for 2018
precipitation_2018_data <- read_excel('./data/Trash-Wheel-Collection-Totals-7-2020-2.xlsx',
                                      sheet = "2018 Precipitation", range = "A2:B14") %>%
  janitor::clean_names() %>%
  mutate(
    year = 2018
  )
precipitation_2018_data
```

    ## # A tibble: 12 × 3
    ##    month total  year
    ##    <dbl> <dbl> <dbl>
    ##  1     1  0.94  2018
    ##  2     2  4.8   2018
    ##  3     3  2.69  2018
    ##  4     4  4.69  2018
    ##  5     5  9.27  2018
    ##  6     6  4.77  2018
    ##  7     7 10.2   2018
    ##  8     8  6.45  2018
    ##  9     9 10.5   2018
    ## 10    10  2.12  2018
    ## 11    11  7.82  2018
    ## 12    12  6.11  2018

``` r
# read and clean precipitation data for 2019
precipitation_2019_data <- read_excel('./data/Trash-Wheel-Collection-Totals-7-2020-2.xlsx',
                                      sheet = "2019 Precipitation", range = "A2:B14") %>%
  janitor::clean_names() %>%
  mutate(
    year = 2019
  )
precipitation_2019_data
```

    ## # A tibble: 12 × 3
    ##    month total  year
    ##    <dbl> <dbl> <dbl>
    ##  1     1  3.1   2019
    ##  2     2  3.64  2019
    ##  3     3  4.47  2019
    ##  4     4  1.46  2019
    ##  5     5  3.58  2019
    ##  6     6  0.42  2019
    ##  7     7  3.85  2019
    ##  8     8  2.39  2019
    ##  9     9  0.16  2019
    ## 10    10  5.45  2019
    ## 11    11  1.86  2019
    ## 12    12  3.57  2019

``` r
# combine dataset and convert month
precipitation_combine_data <- bind_rows(precipitation_2018_data, precipitation_2019_data) %>%
  mutate(
    month = month.name[month]
  )
precipitation_combine_data
```

    ## # A tibble: 24 × 3
    ##    month     total  year
    ##    <chr>     <dbl> <dbl>
    ##  1 January    0.94  2018
    ##  2 February   4.8   2018
    ##  3 March      2.69  2018
    ##  4 April      4.69  2018
    ##  5 May        9.27  2018
    ##  6 June       4.77  2018
    ##  7 July      10.2   2018
    ##  8 August     6.45  2018
    ##  9 September 10.5   2018
    ## 10 October    2.12  2018
    ## # … with 14 more rows

In Mr. Trash wheel dataset, there are 453 observations and 14 variables,
such as “weight\_tons” and “plastic bottles” which are numeric and
numeric respectively.

In the combination dataset, there are there are 24 observations and 3
variables, which are year, month and total. And their types are numeric,
character and numeric.

The total precipitation in 2018 is 70.33.

The median number of sports balls in a dumpster in 2019 is 9.

## Problem 2

``` r
# clean pols-month.csv
pols_month_data <- read_csv(file = './data/fivethirtyeight_datasets/pols-month.csv',
                            show_col_types = FALSE) %>%
  janitor::clean_names() %>%
  separate(mon, c("year","month","day"), sep = "-") %>%
  mutate(
    month = month.name[as.numeric(month)],
    year = as.numeric(year), #solve the problem when datasets join
    president = prez_gop,
    president = replace(president, president > 0, "gop"), #solve the problem that there exists 2 in prez_gop
    president = replace(president, president == 0, "dem"),
  ) %>%
  select(-day,-prez_dem,-prez_gop) #remove appointed columns
pols_month_data
```

    ## # A tibble: 822 × 9
    ##     year month     gov_gop sen_gop rep_gop gov_dem sen_dem rep_dem president
    ##    <dbl> <chr>       <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl> <chr>    
    ##  1  1947 January        23      51     253      23      45     198 dem      
    ##  2  1947 February       23      51     253      23      45     198 dem      
    ##  3  1947 March          23      51     253      23      45     198 dem      
    ##  4  1947 April          23      51     253      23      45     198 dem      
    ##  5  1947 May            23      51     253      23      45     198 dem      
    ##  6  1947 June           23      51     253      23      45     198 dem      
    ##  7  1947 July           23      51     253      23      45     198 dem      
    ##  8  1947 August         23      51     253      23      45     198 dem      
    ##  9  1947 September      23      51     253      23      45     198 dem      
    ## 10  1947 October        23      51     253      23      45     198 dem      
    ## # … with 812 more rows

``` r
# clean the snp.csv
snp_data <- read_csv(file = './data/fivethirtyeight_datasets/snp.csv',
                     show_col_types = FALSE) %>%
  janitor::clean_names() %>%
  mutate(
    date = as.character(mdy(date)) #convert Date to character for separation
  ) %>%
  separate(date, c("year","month","day"), sep = "-") %>%
  mutate(
    month = month.name[as.numeric(month)],
    year = as.numeric(year),
    year = ifelse(year > 2021, year - 100, year) #fix the problem of function mdy()
  ) %>%
  select(year,month,everything(),-day) #arrange and remove appointed columns
snp_data
```

    ## # A tibble: 787 × 3
    ##     year month    close
    ##    <dbl> <chr>    <dbl>
    ##  1  2015 July     2080.
    ##  2  2015 June     2063.
    ##  3  2015 May      2107.
    ##  4  2015 April    2086.
    ##  5  2015 March    2068.
    ##  6  2015 February 2104.
    ##  7  2015 January  1995.
    ##  8  2014 December 2059.
    ##  9  2014 November 2068.
    ## 10  2014 October  2018.
    ## # … with 777 more rows

``` r
# clean the unemployment data
# To ensure that key variables take the same values, convert abb to full name
unemployment_data <- read_csv(file = './data/fivethirtyeight_datasets/unemployment.csv',
                              show_col_types = FALSE) %>%
  pivot_longer(
    Jan:Dec,
    names_to = "month",
    values_to = "unemployment_precentage"
  ) %>%
  mutate(
    month = month.name[match(month,month.abb)] #convert month abbreviation to full name for datasets join
  ) %>%
  janitor::clean_names()
unemployment_data
```

    ## # A tibble: 816 × 3
    ##     year month     unemployment_precentage
    ##    <dbl> <chr>                       <dbl>
    ##  1  1948 January                       3.4
    ##  2  1948 February                      3.8
    ##  3  1948 March                         4  
    ##  4  1948 April                         3.9
    ##  5  1948 May                           3.5
    ##  6  1948 June                          3.6
    ##  7  1948 July                          3.6
    ##  8  1948 August                        3.9
    ##  9  1948 September                     3.8
    ## 10  1948 October                       3.7
    ## # … with 806 more rows

``` r
# join the datasets
combine_data <- left_join(pols_month_data, snp_data, by = c('year','month')) %>%
  left_join(unemployment_data,by = c('year','month'))
combine_data
```

    ## # A tibble: 822 × 11
    ##     year month   gov_gop sen_gop rep_gop gov_dem sen_dem rep_dem president close
    ##    <dbl> <chr>     <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl> <chr>     <dbl>
    ##  1  1947 January      23      51     253      23      45     198 dem          NA
    ##  2  1947 Februa…      23      51     253      23      45     198 dem          NA
    ##  3  1947 March        23      51     253      23      45     198 dem          NA
    ##  4  1947 April        23      51     253      23      45     198 dem          NA
    ##  5  1947 May          23      51     253      23      45     198 dem          NA
    ##  6  1947 June         23      51     253      23      45     198 dem          NA
    ##  7  1947 July         23      51     253      23      45     198 dem          NA
    ##  8  1947 August       23      51     253      23      45     198 dem          NA
    ##  9  1947 Septem…      23      51     253      23      45     198 dem          NA
    ## 10  1947 October      23      51     253      23      45     198 dem          NA
    ## # … with 812 more rows, and 1 more variable: unemployment_precentage <dbl>

The data in pols-month.csv is about number of national politicans who
are democratic or republican at any given time. The dimension of it is
(822, 9) and the range of years is 68. The key variables are year, month
and president, and their types are numeric, character and character.

The data in snap.csv is about S&P stock market index. The dimension of
it is (787, 3) and the range of years is 65. The key variables are year,
month and close, and their types are numeric, character and numeric.

The data in unemployment.csv is about precentage of unemployment at any
given time. The dimension of it is (816, 3) and the range of years is
67. The key variables are year, month and unemployment\_precentage, and
their types are numeric, character and numeric.

The dimension of data in the combination data is (822, 11) and the range
of years is 68. The key variables are year, month, president, close and
unemployment\_precentage, and their types are the same as those in
original datasets.

## Problem 3

``` r
#import and clean data
name_data <- read_csv(file = './data/name.csv',
                      show_col_types = FALSE) %>%
  janitor::clean_names() %>%
  mutate(
    #address the names of a categorical predictor and string variables
    #only capitalize the first letter of every word
    gender = str_to_title(gender),
    ethnicity = str_to_title(ethnicity),
    ethnicity = replace(ethnicity, ethnicity == "Asian And Paci",
                        "Asian And Pacific Islander"),
    ethnicity = replace(ethnicity, ethnicity == "Black Non Hisp", 
                        "Black Non Hispanic"),
    ethnicity = replace(ethnicity, ethnicity == "White Non Hisp", 
                        "White Non Hispanic"),
    childs_first_name = str_to_title(childs_first_name)
  ) %>%
  distinct() #remove duplicate rows
name_data
```

    ## # A tibble: 12,181 × 6
    ##    year_of_birth gender ethnicity                  childs_first_name count  rank
    ##            <dbl> <chr>  <chr>                      <chr>             <dbl> <dbl>
    ##  1          2016 Female Asian And Pacific Islander Olivia              172     1
    ##  2          2016 Female Asian And Pacific Islander Chloe               112     2
    ##  3          2016 Female Asian And Pacific Islander Sophia              104     3
    ##  4          2016 Female Asian And Pacific Islander Emily                99     4
    ##  5          2016 Female Asian And Pacific Islander Emma                 99     4
    ##  6          2016 Female Asian And Pacific Islander Mia                  79     5
    ##  7          2016 Female Asian And Pacific Islander Charlotte            59     6
    ##  8          2016 Female Asian And Pacific Islander Sarah                57     7
    ##  9          2016 Female Asian And Pacific Islander Isabella             56     8
    ## 10          2016 Female Asian And Pacific Islander Hannah               56     8
    ## # … with 12,171 more rows

``` r
#produce a table for Olivia
olivia_data <- filter(name_data, childs_first_name == "Olivia"
                      & gender == "Female") %>%
  pivot_wider(
    ethnicity,
    names_from = "year_of_birth",
    values_from = "rank"
  )
olivia_data
```

    ## # A tibble: 4 × 7
    ##   ethnicity                  `2016` `2015` `2014` `2013` `2012` `2011`
    ##   <chr>                       <dbl>  <dbl>  <dbl>  <dbl>  <dbl>  <dbl>
    ## 1 Asian And Pacific Islander      1      1      1      3      3      4
    ## 2 Black Non Hispanic              8      4      8      6      8     10
    ## 3 Hispanic                       13     16     16     22     22     18
    ## 4 White Non Hispanic              1      1      1      1      4      2

``` r
#produce a table for male
#select 1st name among different ethnicities in different year
male_data <- filter(name_data, rank == 1 & gender == "Male") %>%
  pivot_wider(
    ethnicity,
    names_from = "year_of_birth",
    values_from = "childs_first_name"
  )
male_data
```

    ## # A tibble: 4 × 7
    ##   ethnicity                  `2016` `2015` `2014` `2013` `2012` `2011` 
    ##   <chr>                      <chr>  <chr>  <chr>  <chr>  <chr>  <chr>  
    ## 1 Asian And Pacific Islander Ethan  Jayden Jayden Jayden Ryan   Ethan  
    ## 2 Black Non Hispanic         Noah   Noah   Ethan  Ethan  Jayden Jayden 
    ## 3 Hispanic                   Liam   Liam   Liam   Jayden Jayden Jayden 
    ## 4 White Non Hispanic         Joseph David  Joseph David  Joseph Michael

``` r
#produce a scatter plot
#produce data for scatter plot
plot_data <- name_data %>%
  filter(year_of_birth == "2016" & ethnicity == "White Non Hispanic" 
         & gender == "Male")

#draw the plot
ggplot(plot_data, aes(x = rank, y = count)) +
  geom_point() + 
  labs(
    x = "rank in popularity",
    y = "number of children"
  )
```

<img src="p8105_hw2_kz2411_files/figure-gfm/scatter plot-1.png" width="90%" />
